// app/layout.js
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'MEDXpro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ─── DearFlip core stylesheet ─── */}
        <link
          rel="stylesheet"
          href="/dflip/css/dflip.min.css"
        />
        {/* ─── Iconos Themify para los botones de zoom, fullscreen, etc. ─── */}
        <link
          rel="stylesheet"
          href="/dflip/css/themify-icons.css"
        />
      </head>

      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
