// app/layout.js
import './globals.css';
import { AuthProvider } from './Providers';
import PageTransition from './components/PageTransition';

export const metadata = {
  title: 'MEDXpro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ─── DearFlip core stylesheet ─── */}
        <link
          rel="stylesheet"
          href="/dflip/css/dflip.min.css"
        />
        {/* ─── Iconos Themify para los botones de zoom, fullscreen, etc. ─── */}
        <link
          rel="stylesheet"
          href="/dflip/css/themify-icons.css"
        />
      </head>

      <body>
        <AuthProvider>
          <PageTransition>{children}</PageTransition>
        </AuthProvider>
      </body>
    </html>
  );
}
