
//import Overhead from './components/Overhead'
//import OverheadMenu from './components/OverheadMenu'
//import SubMenu from './components/Submenu'
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'MEDXpro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
        </body>
    </html>
  )
}
